//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSlotting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryTimeSlot
    {
        public int Id { get; set; }
        public int TimeSlotId { get; set; }
        public int CustomerId { get; set; }
        public int SiteId { get; set; }
        public int DriverId { get; set; }
        public int VehicleId { get; set; }
        public int StatusTypeId { get; set; }
        public int ContractId { get; set; }
        public int SupplierId { get; set; }
        public int VendorId { get; set; }
        public int CommodityId { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public Nullable<int> Tons { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int CreatedBy { get; set; }
        public int ModifiedBy { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Site Site { get; set; }
        public virtual StatusType StatusType { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual TimeSlot TimeSlot { get; set; }
        public virtual Vehicle Vehicle { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual WebUser WebUser { get; set; }
        public virtual Commodity Commodity { get; set; }
    }
}
