//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSlotting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailLog
    {
        public int Id { get; set; }
        public Nullable<int> WebUserId { get; set; }
        public string Recipient { get; set; }
        public string Subject { get; set; }
        public string Attachment { get; set; }
        public string URL { get; set; }
        public string Filename { get; set; }
        public string SendError { get; set; }
        public System.DateTime SentDate { get; set; }
    }
}
