namespace TimeSlotting.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class DatabaseForeignKeysForCreatedBy : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.WebUsers", "CustomerId", "dbo.Customers");
            DropForeignKey("dbo.WebUsers", "FleetId", "dbo.Fleets");
            DropForeignKey("dbo.DeliveryTimeSlots", "DriverId", "dbo.WebUsers");
            DropForeignKey("dbo.WebUsers", "SiteId", "dbo.Sites");
            AddColumn("dbo.Commodities", "CreatedById", c => c.Int(nullable: false));
            AddColumn("dbo.Commodities", "ModifiedById", c => c.Int(nullable: false));
            AddColumn("dbo.DeliveryTimeSlots", "CreatedById", c => c.Int(nullable: false));
            AddColumn("dbo.DeliveryTimeSlots", "ModifiedById", c => c.Int(nullable: false));
            AddColumn("dbo.DeliveryTimeSlots", "WebUser_Id", c => c.Int());
            AddColumn("dbo.Contracts", "CreatedById", c => c.Int(nullable: false));
            AddColumn("dbo.Contracts", "ModifiedById", c => c.Int(nullable: false));
            AddColumn("dbo.Customers", "CreatedById", c => c.Int(nullable: false));
            AddColumn("dbo.Customers", "ModifiedById", c => c.Int(nullable: false));
            AddColumn("dbo.Fleets", "CreatedById", c => c.Int(nullable: false));
            AddColumn("dbo.Fleets", "ModifiedById", c => c.Int(nullable: false));
            AddColumn("dbo.Vehicles", "CreatedById", c => c.Int(nullable: false));
            AddColumn("dbo.Vehicles", "ModifiedById", c => c.Int(nullable: false));
            AddColumn("dbo.WebUsers", "CreatedById", c => c.Int());
            AddColumn("dbo.WebUsers", "ModifiedById", c => c.Int());
            AddColumn("dbo.WebUsers", "Site_Id", c => c.Int());
            AddColumn("dbo.WebUsers", "Fleet_Id", c => c.Int());
            AddColumn("dbo.WebUsers", "Customer_Id", c => c.Int());
            AddColumn("dbo.Sites", "CreatedById", c => c.Int(nullable: false));
            AddColumn("dbo.Sites", "ModifiedById", c => c.Int(nullable: false));
            AddColumn("dbo.StatusTypes", "CreatedById", c => c.Int(nullable: false));
            AddColumn("dbo.StatusTypes", "ModifiedById", c => c.Int(nullable: false));
            AddColumn("dbo.Suppliers", "CreatedById", c => c.Int(nullable: false));
            AddColumn("dbo.Suppliers", "ModifiedById", c => c.Int(nullable: false));
            AddColumn("dbo.TimeSlots", "CreatedById", c => c.Int(nullable: false));
            AddColumn("dbo.TimeSlots", "ModifiedById", c => c.Int(nullable: false));
            AddColumn("dbo.Vendors", "CreatedById", c => c.Int(nullable: false));
            AddColumn("dbo.Vendors", "ModifiedById", c => c.Int(nullable: false));
            CreateIndex("dbo.Commodities", "CreatedById");
            CreateIndex("dbo.Commodities", "ModifiedById");
            CreateIndex("dbo.WebUsers", "CreatedById");
            CreateIndex("dbo.WebUsers", "ModifiedById");
            CreateIndex("dbo.WebUsers", "Site_Id");
            CreateIndex("dbo.WebUsers", "Fleet_Id");
            CreateIndex("dbo.WebUsers", "Customer_Id");
            CreateIndex("dbo.Customers", "CreatedById");
            CreateIndex("dbo.Customers", "ModifiedById");
            CreateIndex("dbo.DeliveryTimeSlots", "CreatedById");
            CreateIndex("dbo.DeliveryTimeSlots", "ModifiedById");
            CreateIndex("dbo.DeliveryTimeSlots", "WebUser_Id");
            CreateIndex("dbo.Contracts", "CreatedById");
            CreateIndex("dbo.Contracts", "ModifiedById");
            CreateIndex("dbo.Sites", "CreatedById");
            CreateIndex("dbo.Sites", "ModifiedById");
            CreateIndex("dbo.StatusTypes", "CreatedById");
            CreateIndex("dbo.StatusTypes", "ModifiedById");
            CreateIndex("dbo.Suppliers", "CreatedById");
            CreateIndex("dbo.Suppliers", "ModifiedById");
            CreateIndex("dbo.TimeSlots", "CreatedById");
            CreateIndex("dbo.TimeSlots", "ModifiedById");
            CreateIndex("dbo.Vehicles", "CreatedById");
            CreateIndex("dbo.Vehicles", "ModifiedById");
            CreateIndex("dbo.Fleets", "CreatedById");
            CreateIndex("dbo.Fleets", "ModifiedById");
            CreateIndex("dbo.Vendors", "CreatedById");
            CreateIndex("dbo.Vendors", "ModifiedById");
            AddForeignKey("dbo.WebUsers", "CreatedById", "dbo.WebUsers", "Id");
            AddForeignKey("dbo.Customers", "CreatedById", "dbo.WebUsers", "Id", cascadeDelete: false);
            AddForeignKey("dbo.Contracts", "CreatedById", "dbo.WebUsers", "Id", cascadeDelete: false);
            AddForeignKey("dbo.Contracts", "ModifiedById", "dbo.WebUsers", "Id", cascadeDelete: false);
            AddForeignKey("dbo.DeliveryTimeSlots", "CreatedById", "dbo.WebUsers", "Id", cascadeDelete: false);
            AddForeignKey("dbo.DeliveryTimeSlots", "ModifiedById", "dbo.WebUsers", "Id", cascadeDelete: false);
            AddForeignKey("dbo.Sites", "CreatedById", "dbo.WebUsers", "Id", cascadeDelete: false);
            AddForeignKey("dbo.Sites", "ModifiedById", "dbo.WebUsers", "Id", cascadeDelete: false);
            AddForeignKey("dbo.StatusTypes", "CreatedById", "dbo.WebUsers", "Id", cascadeDelete: false);
            AddForeignKey("dbo.StatusTypes", "ModifiedById", "dbo.WebUsers", "Id", cascadeDelete: false);
            AddForeignKey("dbo.Suppliers", "CreatedById", "dbo.WebUsers", "Id", cascadeDelete: false);
            AddForeignKey("dbo.Suppliers", "ModifiedById", "dbo.WebUsers", "Id", cascadeDelete: false);
            AddForeignKey("dbo.TimeSlots", "CreatedById", "dbo.WebUsers", "Id", cascadeDelete: false);
            AddForeignKey("dbo.TimeSlots", "ModifiedById", "dbo.WebUsers", "Id", cascadeDelete: false);
            AddForeignKey("dbo.Vehicles", "CreatedById", "dbo.WebUsers", "Id", cascadeDelete: false);
            AddForeignKey("dbo.Fleets", "CreatedById", "dbo.WebUsers", "Id", cascadeDelete: false);
            AddForeignKey("dbo.Fleets", "ModifiedById", "dbo.WebUsers", "Id", cascadeDelete: false);
            AddForeignKey("dbo.Vehicles", "ModifiedById", "dbo.WebUsers", "Id", cascadeDelete: false);
            AddForeignKey("dbo.Vendors", "CreatedById", "dbo.WebUsers", "Id", cascadeDelete: false);
            AddForeignKey("dbo.Vendors", "ModifiedById", "dbo.WebUsers", "Id", cascadeDelete: false);
            AddForeignKey("dbo.Customers", "ModifiedById", "dbo.WebUsers", "Id", cascadeDelete: false);
            AddForeignKey("dbo.WebUsers", "ModifiedById", "dbo.WebUsers", "Id");
            AddForeignKey("dbo.Commodities", "CreatedById", "dbo.WebUsers", "Id", cascadeDelete: false);
            AddForeignKey("dbo.Commodities", "ModifiedById", "dbo.WebUsers", "Id", cascadeDelete: false);
            AddForeignKey("dbo.WebUsers", "Customer_Id", "dbo.Customers", "Id");
            AddForeignKey("dbo.WebUsers", "Fleet_Id", "dbo.Fleets", "Id");
            AddForeignKey("dbo.DeliveryTimeSlots", "WebUser_Id", "dbo.WebUsers", "Id");
            AddForeignKey("dbo.WebUsers", "Site_Id", "dbo.Sites", "Id");
            DropColumn("dbo.Commodities", "CreatedBy");
            DropColumn("dbo.Commodities", "ModifiedBy");
            DropColumn("dbo.DeliveryTimeSlots", "CreatedBy");
            DropColumn("dbo.DeliveryTimeSlots", "ModifiedBy");
            DropColumn("dbo.Contracts", "CreatedBy");
            DropColumn("dbo.Contracts", "ModifiedBy");
            DropColumn("dbo.Customers", "CreatedBy");
            DropColumn("dbo.Customers", "ModifiedBy");
            DropColumn("dbo.Fleets", "CreatedBy");
            DropColumn("dbo.Fleets", "ModifiedBy");
            DropColumn("dbo.Vehicles", "CreatedBy");
            DropColumn("dbo.Vehicles", "ModifiedBy");
            DropColumn("dbo.WebUsers", "CreatedBy");
            DropColumn("dbo.WebUsers", "ModifiedBy");
            DropColumn("dbo.Sites", "CreatedBy");
            DropColumn("dbo.Sites", "ModifiedBy");
            DropColumn("dbo.StatusTypes", "CreatedBy");
            DropColumn("dbo.StatusTypes", "ModifiedBy");
            DropColumn("dbo.Suppliers", "CreatedBy");
            DropColumn("dbo.Suppliers", "ModifiedBy");
            DropColumn("dbo.TimeSlots", "CreatedBy");
            DropColumn("dbo.TimeSlots", "ModifiedBy");
            DropColumn("dbo.Vendors", "CreatedBy");
            DropColumn("dbo.Vendors", "ModifiedBy");
        }
        
        public override void Down()
        {
            AddColumn("dbo.Vendors", "ModifiedBy", c => c.Int(nullable: false));
            AddColumn("dbo.Vendors", "CreatedBy", c => c.Int(nullable: false));
            AddColumn("dbo.TimeSlots", "ModifiedBy", c => c.Int(nullable: false));
            AddColumn("dbo.TimeSlots", "CreatedBy", c => c.Int(nullable: false));
            AddColumn("dbo.Suppliers", "ModifiedBy", c => c.Int(nullable: false));
            AddColumn("dbo.Suppliers", "CreatedBy", c => c.Int(nullable: false));
            AddColumn("dbo.StatusTypes", "ModifiedBy", c => c.Int(nullable: false));
            AddColumn("dbo.StatusTypes", "CreatedBy", c => c.Int(nullable: false));
            AddColumn("dbo.Sites", "ModifiedBy", c => c.Int(nullable: false));
            AddColumn("dbo.Sites", "CreatedBy", c => c.Int(nullable: false));
            AddColumn("dbo.WebUsers", "ModifiedBy", c => c.Int(nullable: false));
            AddColumn("dbo.WebUsers", "CreatedBy", c => c.Int(nullable: false));
            AddColumn("dbo.Vehicles", "ModifiedBy", c => c.Int(nullable: false));
            AddColumn("dbo.Vehicles", "CreatedBy", c => c.Int(nullable: false));
            AddColumn("dbo.Fleets", "ModifiedBy", c => c.Int(nullable: false));
            AddColumn("dbo.Fleets", "CreatedBy", c => c.Int(nullable: false));
            AddColumn("dbo.Customers", "ModifiedBy", c => c.Int(nullable: false));
            AddColumn("dbo.Customers", "CreatedBy", c => c.Int(nullable: false));
            AddColumn("dbo.Contracts", "ModifiedBy", c => c.Int(nullable: false));
            AddColumn("dbo.Contracts", "CreatedBy", c => c.Int(nullable: false));
            AddColumn("dbo.DeliveryTimeSlots", "ModifiedBy", c => c.Int(nullable: false));
            AddColumn("dbo.DeliveryTimeSlots", "CreatedBy", c => c.Int(nullable: false));
            AddColumn("dbo.Commodities", "ModifiedBy", c => c.Int(nullable: false));
            AddColumn("dbo.Commodities", "CreatedBy", c => c.Int(nullable: false));
            DropForeignKey("dbo.WebUsers", "Site_Id", "dbo.Sites");
            DropForeignKey("dbo.DeliveryTimeSlots", "WebUser_Id", "dbo.WebUsers");
            DropForeignKey("dbo.WebUsers", "Fleet_Id", "dbo.Fleets");
            DropForeignKey("dbo.WebUsers", "Customer_Id", "dbo.Customers");
            DropForeignKey("dbo.Commodities", "ModifiedById", "dbo.WebUsers");
            DropForeignKey("dbo.Commodities", "CreatedById", "dbo.WebUsers");
            DropForeignKey("dbo.WebUsers", "ModifiedById", "dbo.WebUsers");
            DropForeignKey("dbo.Customers", "ModifiedById", "dbo.WebUsers");
            DropForeignKey("dbo.Vendors", "ModifiedById", "dbo.WebUsers");
            DropForeignKey("dbo.Vendors", "CreatedById", "dbo.WebUsers");
            DropForeignKey("dbo.Vehicles", "ModifiedById", "dbo.WebUsers");
            DropForeignKey("dbo.Fleets", "ModifiedById", "dbo.WebUsers");
            DropForeignKey("dbo.Fleets", "CreatedById", "dbo.WebUsers");
            DropForeignKey("dbo.Vehicles", "CreatedById", "dbo.WebUsers");
            DropForeignKey("dbo.TimeSlots", "ModifiedById", "dbo.WebUsers");
            DropForeignKey("dbo.TimeSlots", "CreatedById", "dbo.WebUsers");
            DropForeignKey("dbo.Suppliers", "ModifiedById", "dbo.WebUsers");
            DropForeignKey("dbo.Suppliers", "CreatedById", "dbo.WebUsers");
            DropForeignKey("dbo.StatusTypes", "ModifiedById", "dbo.WebUsers");
            DropForeignKey("dbo.StatusTypes", "CreatedById", "dbo.WebUsers");
            DropForeignKey("dbo.Sites", "ModifiedById", "dbo.WebUsers");
            DropForeignKey("dbo.Sites", "CreatedById", "dbo.WebUsers");
            DropForeignKey("dbo.DeliveryTimeSlots", "ModifiedById", "dbo.WebUsers");
            DropForeignKey("dbo.DeliveryTimeSlots", "CreatedById", "dbo.WebUsers");
            DropForeignKey("dbo.Contracts", "ModifiedById", "dbo.WebUsers");
            DropForeignKey("dbo.Contracts", "CreatedById", "dbo.WebUsers");
            DropForeignKey("dbo.Customers", "CreatedById", "dbo.WebUsers");
            DropForeignKey("dbo.WebUsers", "CreatedById", "dbo.WebUsers");
            DropIndex("dbo.Vendors", new[] { "ModifiedById" });
            DropIndex("dbo.Vendors", new[] { "CreatedById" });
            DropIndex("dbo.Fleets", new[] { "ModifiedById" });
            DropIndex("dbo.Fleets", new[] { "CreatedById" });
            DropIndex("dbo.Vehicles", new[] { "ModifiedById" });
            DropIndex("dbo.Vehicles", new[] { "CreatedById" });
            DropIndex("dbo.TimeSlots", new[] { "ModifiedById" });
            DropIndex("dbo.TimeSlots", new[] { "CreatedById" });
            DropIndex("dbo.Suppliers", new[] { "ModifiedById" });
            DropIndex("dbo.Suppliers", new[] { "CreatedById" });
            DropIndex("dbo.StatusTypes", new[] { "ModifiedById" });
            DropIndex("dbo.StatusTypes", new[] { "CreatedById" });
            DropIndex("dbo.Sites", new[] { "ModifiedById" });
            DropIndex("dbo.Sites", new[] { "CreatedById" });
            DropIndex("dbo.Contracts", new[] { "ModifiedById" });
            DropIndex("dbo.Contracts", new[] { "CreatedById" });
            DropIndex("dbo.DeliveryTimeSlots", new[] { "WebUser_Id" });
            DropIndex("dbo.DeliveryTimeSlots", new[] { "ModifiedById" });
            DropIndex("dbo.DeliveryTimeSlots", new[] { "CreatedById" });
            DropIndex("dbo.Customers", new[] { "ModifiedById" });
            DropIndex("dbo.Customers", new[] { "CreatedById" });
            DropIndex("dbo.WebUsers", new[] { "Customer_Id" });
            DropIndex("dbo.WebUsers", new[] { "Fleet_Id" });
            DropIndex("dbo.WebUsers", new[] { "Site_Id" });
            DropIndex("dbo.WebUsers", new[] { "ModifiedById" });
            DropIndex("dbo.WebUsers", new[] { "CreatedById" });
            DropIndex("dbo.Commodities", new[] { "ModifiedById" });
            DropIndex("dbo.Commodities", new[] { "CreatedById" });
            DropColumn("dbo.Vendors", "ModifiedById");
            DropColumn("dbo.Vendors", "CreatedById");
            DropColumn("dbo.TimeSlots", "ModifiedById");
            DropColumn("dbo.TimeSlots", "CreatedById");
            DropColumn("dbo.Suppliers", "ModifiedById");
            DropColumn("dbo.Suppliers", "CreatedById");
            DropColumn("dbo.StatusTypes", "ModifiedById");
            DropColumn("dbo.StatusTypes", "CreatedById");
            DropColumn("dbo.Sites", "ModifiedById");
            DropColumn("dbo.Sites", "CreatedById");
            DropColumn("dbo.WebUsers", "Customer_Id");
            DropColumn("dbo.WebUsers", "Fleet_Id");
            DropColumn("dbo.WebUsers", "Site_Id");
            DropColumn("dbo.WebUsers", "ModifiedById");
            DropColumn("dbo.WebUsers", "CreatedById");
            DropColumn("dbo.Vehicles", "ModifiedById");
            DropColumn("dbo.Vehicles", "CreatedById");
            DropColumn("dbo.Fleets", "ModifiedById");
            DropColumn("dbo.Fleets", "CreatedById");
            DropColumn("dbo.Customers", "ModifiedById");
            DropColumn("dbo.Customers", "CreatedById");
            DropColumn("dbo.Contracts", "ModifiedById");
            DropColumn("dbo.Contracts", "CreatedById");
            DropColumn("dbo.DeliveryTimeSlots", "WebUser_Id");
            DropColumn("dbo.DeliveryTimeSlots", "ModifiedById");
            DropColumn("dbo.DeliveryTimeSlots", "CreatedById");
            DropColumn("dbo.Commodities", "ModifiedById");
            DropColumn("dbo.Commodities", "CreatedById");
            AddForeignKey("dbo.WebUsers", "SiteId", "dbo.Sites", "Id");
            AddForeignKey("dbo.DeliveryTimeSlots", "DriverId", "dbo.WebUsers", "Id", cascadeDelete: true);
            AddForeignKey("dbo.WebUsers", "FleetId", "dbo.Fleets", "Id");
            AddForeignKey("dbo.WebUsers", "CustomerId", "dbo.Customers", "Id");
        }
    }
}
